accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountCreateView,
    AccountListView,
    # ExpenseCategoryCreateView,
    ReceiptListView,
    category_list,
    expense_category_create,
    receipt_create,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="account_create"
    ),
    path("create/", receipt_create, name="receipt_create"),
    path(
        "categories/create/",
        expense_category_create,
        name="category_create",
    ),
    path("categories/", category_list, name="category_list"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="catgories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    catgory = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def __str__(self):
        return "$" + str(self.total + self.tax) + " from " + self.vendor

receipts/forms.py
from django.forms import ModelForm
from receipts.models import ExpenseCategory, Receipt


class ExpenseCategoryForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ["name"]


class ReceiptForm(ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "catgory", "account"]

accounts/views.py
from django.shortcuts import redirect, render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.forms import ExpenseCategoryForm, ReceiptForm
from receipts.models import Account, ExpenseCategory, Receipt

from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


@login_required
def expense_category_create(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.owner = request.user
            category.save()
            return redirect("home")
    else:
        form = ExpenseCategoryForm(request.POST)
    context = {"form": form}
    return render(request, "categories/create.html", context)


"""class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")"""


@login_required
def receipt_create(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.purchaser = request.user
            category.save()
            return redirect("home")
    else:
        form = ReceiptForm(request.POST)
    context = {"form": form}
    return render(request, "receipts/create.html", context)


@login_required
def category_list(request):
    context = {
        "categories": ExpenseCategory.objects.filter(owner=request.user)
    }
    return render(request, "categories/list.html", context)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expenses</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        {% if user.is_authenticated %}
        <a class="head_item" href="{% url 'home' %}">Home</a>
        <a class="head_item" href="{% url 'category_list' %}">Category List</a>
        <a class="head_item" href="{% url 'account_list' %}">Account List</a>
        <a class="head_item" href="{% url 'receipt_create' %}">Create Receipt</a>
        <a class="head_item" href="{% url 'account_create' %}">Create Account</a>
        <a class="head_item" href="{% url 'category_create' %}">Create Category</a>
        <a class="head_item" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="head_item" href="{% url 'login' %}">Login</a>
        <a class="head_item" href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </header>
    {% block content %}
    {% endblock content %}

</body>

</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}
{% block content %}
<div class="form_type">
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>
            Create
        </button>
    </form>
</div>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}
{% block content %}
<h1>Account List</h1>
<table>
    <thead>
        <tr class="table_background">
            <th>Name</th>
            <th>Number</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr class="{% cycle 'table_background1' '' %}">
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/categories/create.html
{% extends 'base.html' %}
{% block content %}
<div class="form_type">
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>
            Create
        </button>
    </form>
</div>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}
{% block content %}
<h1>Category List</h1>
<table>
    <thead>
        <tr class="table_background">
            <th>Name</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr class="{% cycle 'table_background1' '' %}">
            <td>{{ category.name }}</td>
            <td>{{ category.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
<div class="form_type">
    <h1>Create Receipt</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>
            Create
        </button>
    </form>
</div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<h1>Receipt List</h1>
<table>
    <thead>
        <tr class="table_background">
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr class="{% cycle 'table_background1' '' %}">
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date|date:'m-d-Y' }}</td>
            <td>{{ receipt.catgory.name }}</td>
            <td>{{ receipt.account.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}